data_params:
  train_data_path: "data/data.csv"
  scalers_path: "artefacts/scalers.json"
  model_path: "artefacts/"
  model_columns:
    - Mileage
    - Age
    - Volume_1.2
    - Volume_1.4
    - Volume_1.6
    - Volume_2.0
    - automatic_gearbox
    - Private
    - 3-doors
  binary_columns:
    - 3-doors
    - Private
  target_column: Price
  numerical_columns:
    - Mileage
    - Age
  cheap_car_threshold: 300000
  overused_car_threshold: 200000
  n_cv_splits: 3

model_params:
  lasso_params:
    alpha: 1.0
    max_iter: 10000
  random_forest_params:
    n_estimators: 1000
  boosting_params:
    n_estimators: 1000
    learning_rate: 0.005
